urls.py
from django.urls import include, re_path as url, path, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
import django.views.static
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.views.decorators.cache import never_cache

import settings
from bib import documentos, prestamos, busqueda
from clinicaestetica import historclinico
from med import alu_medical, box_medical, per_medical
from reportesexcel import reporteexcel, listadofacturas, listadoncreditos, eval_alumdoce_resumen, cronograma, \
    exc_egresados, vinculacion_practicas, proceso_titulacion, xls_seguimiento_graduados, eficiencia, resumen_egresados, \
    materias_por_grupo, estado_cta_por_nivel, gestion_carrera, seguimiento_grupo, valores_inscritos_por_usuario, \
    matriculados_sms, estudiantes_xcarreraysexo, inscritos_general, alumnosporgrupo, conduccion_estudiantes_xperiodo, \
    cobroscontarjetas, informacion_estudiantes, sms_porcarrera, xls_inscritos_porrangofecha, clasesimpartidas, \
    pedagogia, vencimiento_xvencer_estudiantes, vencidos_xvencer_xrubros, matriculados_cne, especies_valoradas, \
    materiasnivelabierto_xgrupo, estudiantes_xgrupo, gestion_moraxnivel, gestion_moraxcarrera, retirados_porrangofecha, \
    listado_sinvinculacion_sinpracticas, distributivo_aulas, matriculados_extranjeros, xls_matriculados_xrangofechas, \
    cobrosonline, resumen_cartera, pagos_gestion, datos_estudiantes, xgrupo_practicas_vinculacion, \
    absentos_porrangofecha, ingresos_caja_fecha, cobros_rango_fecha, cobros_rango_fecha_jornada, \
    rubros_xvencer_matriculados, asistenciasxnivel, xlsmatriculadosxprovincias, becados_xperiodo, \
    indicadores_fichasocioecon, promocion_estudiantes, nivelsocioecon_xperiodo, pagopymentez, estudiantemallasinpago, \
    mallacompletaconsulta, excelprovcanparsec, seguimientograduado_rangofecha, deuda_estudiantes, bandeja_atencion, \
    listadoalumnosmatriculadogrupo, movimientos_reasignacion, actividad_vinculacion_porrangofecha, alumnos_xetnia, \
    est_carga_masiva_estudiantes, cpe_carga_masiva_carreras_estudiante, resumen_sesionescajas, \
    mat_carga_masiva_matriculas, estgeneral_carga_masiva_estudiantes, lib_carga_masiva, informacion_alumnos, \
    cantidad_alumnos_matriculadosxcarreras, segregado_tramites_solicitudes, pagos_tiporubrosestudiante, \
    inscritosporanio, matriculadospagoinscripcion, asistenciasxperiodoycarrera, estudiantesxconvenios, \
    ingresos_formadepago, base_matriculados, xls_descuentosaplicados, gruposetarios, alumnos_socioeconomica, \
    matriz_graduados, caces_estudiantes_rangofecha, caces_estudiantes_periodo, caces_becados, \
    caces_estudiantes_practicas, caces_proyecto_participantes, graduados_sinpracticas, estudiantesfamiliar, \
    xls_terminos_constancia_inscritos, horaspracticasporrol, calificacionesyasistenciasxperiodocarreranivel, \
    valoresvencidos_xperiodo_xcoordinacion, horaspracticasporrangodefechas, descuentos_promociones, \
    xls_graduadosxanioycarrera, xls_informacion_alumnosxgrupo, xls_graduados_condiscapacidad, \
    xls_estudiantes_condiscapacidad, graduados_general, mesadeayuda_porrangofechas, tiemporespuesta_bandejadocente, \
    xls_pagos_nivel_descuento, xls_absentosyretirados_porfacultad, xls_deudasinscripciones_xcoordinacion, \
    xls_asistencias_xcoordinacion, xls_personalitb, xls_registrovacunas, xls_inscripciones_gads, materias_culminadas, \
    xls_vacunasregistroxfacultades, bandejacajeros_xrangofechas, inscritos_xcanton, xls_estudiantes_informaciondobe, \
    xls_inscritos_xprovincia, compromisopagos_xfechas, inscritos_cursosingles, xls_docentesactivos, \
    datapichincha_matriculados, xls_especiesvaloradasxdepartamento, formasdepago_ingresos, xls_cierreclases_porfacultad, \
    xls_clasescerradasdocentes_porfacultad, xls_documentos_bib, cant_inscritos_xcarrera, calificaciones_xnivel, \
    xls_referidos_cobro, xls_infosocioeconomica, tiempo_tramites_bandeja, xls_visitabibliotecaxcarrera, \
    listadoprogramasvinculacion, listadoproyectosvinculacion, listadoaccesobiblioteca, listadodocentes, \
    totalestudiantesxanio, xls_convenios, xls_listadocentesporingreso, xls_entrega_uniformes_admision, \
    xls_pago_sustentaciones_docente, xls_sesiones_caja, xls_promocionuniformes, xls_informacionitb, \
    xls_resumen_visitasbiblioteca, xls_matriculados_xperiodo
from sga import (preguntatestingreso, respuestatestingreso, inscribiralumnos, inscripciontest, columnatestarrastar, \
    encuestaitb, commonviews, reportes, reporteria, solicitudes, retirados, mallas, niveles, horarios, becas_matricula, \
    docentes, administrativos, inscripciones, pre_inscripciones, matriculas, pro_clases, pro_horarios, pro_asistencias, \
    pro_evaluaciones, pro_documentos, pro_autoevaluacion, pro_aluevaluacion, pro_coordevaluacion, pro_alureprobados, \
    pro_titulacion, pro_cronograma, cons_documentos, alu_horarios, alu_materias, alu_notas, alu_solicitudes, \
    alu_documentos, graduados, egresados, alu_finanzas, alu_malla, alu_cronograma, asignaturas, cons_mallas, \
    cons_alumnos, consultas, adm_docentes, noticias, incidencias, dobe, becados, fecha_evaluaciones, distributivo, \
    recepcion_actas, caja, finanzas, facturas, notacredito, recibocaja, vale_caja, recibo_caja, cheques, \
    adm_evaluaciondocentes, adm_grupos, api, estadisticas, rol_pago, prestamo_inst, pro_multas, adm_calendario, \
    calendario, visitabiblioteca, sesiones_caja, qr, dbf, materias_externas, encuestas, cronograma_pagos, \
    estudiantesxdesertar, printdoc, becarios, plan12, justificacion, elimado_matricula, practicasconduc, alumnopractica, \
    practicasadmin, visitabox, test_propedeutico, carrera_admi, inscripcionescurso, gruposcurso, admin_vehiculos, \
    consultafactura, alu_facturacion_electronica, facturacion_electronica, registromedicamento, suministrobox, \
    tipomedicamento, admin_tutoria, profe_tutoria, admin_detalle_tutoria, tutoria, visitabtiket, tiketsturnos, \
    tipooficio, oficios, practicaclase, congreso, descuentos, turno, vistaturno, atencioncliente, newstiket, \
    turnotikets, guarderia, registroguarderia, documentos_alu, estadisticaguarderia, recaudacion, tipovisbox, nee, \
    discapacidad, consultaalumno, seguimiento, registros, resoluciones, seminario, alu_seminario, beca_solicitud, \
    vinculacion, consultagraduados_condu, consultaevaluaciones, absentismo, convenios, programas, cons_niveles, \
    cons_matriculas, periodo, asistente_estudiantiles, incidencia_x_administrativa, consultamovil, alu_panel, panel, \
    seguimiento_inscrip, syllabus, absentismo_finaliza, mantenimiento, alu_referidos, referidos, cita, \
    admin_examencondu, examen_conduc, aula_administracion, inscripcionesaspirantes, consultadocente, enviocorreo, \
    colegio, conveniobox, tipoconvenio, preciobox, pagowester, archivowester, convenio_academico, controlespecies, \
    examen_convalidac, incidencia_doc, requerimiento_x_depart, solicitudonline, archivos_generales, facturacioncronoff, \
    pro_publicaciones, ponencia, mensajetexto, documentos_vinculacion, adminexamenexterno, admintest, examenexterno, \
    listapersonaext, mtto_sectores, externos, tipoprogramas, pagospedagogia, datoscongreso, pago_online, pypagos, \
    nuevoreportecarrera, prueba_psicologica, alcance_notas, aprobacion_alcance_notas, pacifico, especies_admin, \
    entrega_uniforme_municipio, cuentabancaria, preguntaasignatura, profe_examenparcial, inscrip_examenparcial, \
    adminprofeexamen, conduceonline, pagosconduceonline, perfil_profesormateria, jornada, vendedor, \
    admin_grupo_municipio, promociones, alu_matricula, pro_entrega_acta, admin_ayudafinanciera, matriculaseliminadas, \
    empresaconvenio, bancos, alcance_nivelcerrado, aprobacion_nivelcerrado, requeri_soporte, soportetics, pro_especies, \
    archivopichincha, tutorcongreso, tutor_matricula, verrequerimiento, tutor_grupo, multa_docente_materia, \
    bandeja_asistente, webinar, revisionsolicitudpagos, liberarmatricula, eliminados_alcancenotas, escenariopractica, \
    solicitudpracticas, solicitudpracticaadm, supervisarevalest, paramevalpract, entregauniformes, chat, \
    chatsoporte_admin, parametrodescuento, permisosga, tallauniforme, coloruniforme, aulaman, tallazapato, colorzapato, \
    empresasinconvenio, horarioasisitentesolicitudes, clientefactura, inscripcionpostulacion, \
    pago_sustentaciones_docente, sedemantenimiento, encuestatut, ambitoencuestatutor, encuestatutor, \
    encuestainscripcion, encuestaestudiante, alum_tutorias, pagopracticas_docente, cab, \
    actividades_vinculacion_docentes, profesionalizacion, infocont, actividadesextra, evaluaciondocenteman, \
    evaluacionesdocente, alu_evaluaciondocente, doc_evaluaciondocente, doc_evaluaciondirectivo, localizacion_gps, \
    resultadosevaluacion, tipoestadosolicitud, archivosolicitudbeca, tipogestionbeca, solicitudatencion, solicitudadmin, \
    bibliotecavirtual, notificaciones, notificaciones_mant, busqueda_usuario, testingreso, evaluaciondecano, \
    man_referenciasweb, man_otrasbibliotecas, solicitud_materiaonline, encuestadesercion, solicitudpostulacionbeca, \
    solicitudpostulacionbecaadmin, estadisticasadmin, api_rest, vertestingresoitb, tutoria_pedagogica, \
    cons_encuestaingreso, conveniocarrera, solicitudpostulacionbecadjudicada, pro_aulavirtual, \
    adm_cronogramaacademico, distributivodocente, pro_calificaciones, aprobarsilabo,
    cons_encuestaingreso, conveniocarrera, solicitudpostulacionbecadjudicada, admin_teleclinica, teleclinica, \
    solicitudpostulacionbecasoftware)
from sga.templatetags import sga_extras
from socioecon import alu_socioecon, cons_socioecon

admin.autodiscover()
# handler404 = commonviews.page_404
# handler500 = login_user

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if not settings.DEBUG:
    urlpatterns = [

documental/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
from core.my_model import ModelBase


def upload_repository_directory_path(instance, filename):
    ahora = datetime.now()
    return 'repositorio/{0}/{1}/{2}/{3}/{4}'.format(
        instance.get_tipo_display().lower(),
        ahora.year,
        f'{ahora.month:02d}',
        f'{ahora.day:02d}',
        filename
    )


class Repositorio(ModelBase):
    class Tipos(models.IntegerChoices):
        NINGUNO = 0, "Ninguno"
        PDF = 1, "PDF"
        IMAGE = 2, "Imagen"
        WORD = 3, "Word"
        EXCEL = 4, "Excel"

    nombre = models.CharField(verbose_name='Nombre', max_length=350)
    tipo = models.IntegerField(choices=Tipos.choices, default=Tipos.NINGUNO, verbose_name='Tipo')
    archivo = models.FileField(upload_to=upload_repository_directory_path, verbose_name='Archivo')

    def __str__(self):
        return self.nombre

moodle/models.py
# -*- coding: utf-8 -*-
import sys
from decimal import Decimal
from settings import DEBUG
from datetime import datetime
from django.contrib.auth.models import User
from django.db import connections, transaction
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from hashlib import md5


class UserAuth(models.Model):
    user = models.OneToOneField(User, db_index=True, on_delete=models.CASCADE)
    username = models.CharField(default='', max_length=100, verbose_name=u'Nombre de usuario', db_index=True, unique=True)
    password = models.CharField(default='', max_length=1000, verbose_name=u"Contraseña")
    first_name = models.CharField(default='', max_length=250, verbose_name=u"Nombres")
    last_name = models.CharField(default='', max_length=250, verbose_name=u"Apellidos")
    email = models.CharField(default='', max_length=200, verbose_name=u"Correo Institucional")
    city = models.CharField(default='Guayaquil', max_length=150, verbose_name=u"Ciudad")

    def __str__(self):
        return u'%s - %s %s' % (self.username, self.first_name, self.last_name)

    class Meta:
        verbose_name = u"Moodle Usuario"
        verbose_name_plural = u"Moodle Usuarios"
        ordering = ['username']

    def get_person(self):
        from sga.models import Persona
        try:
            return Persona.objects.get(usuario=self.user)
        except ObjectDoesNotExist:
            return None

    def set_data(self):
        ePerson = self.get_person()
        if self.user and ePerson:
            self.username = self.user.username
            self.first_name = ePerson.get_nombres()
            self.last_name = ePerson.get_apellidos()
            self.email = ePerson.emailinst.strip()
            self.city = ePerson.ciudad if ePerson.ciudad else "Guayaquil"

    def check_data(self):
        isUpdate = False
        ePerson = self.get_person()
        first_name = ePerson.get_nombres()
        last_name = ePerson.get_apellidos()
        email = ePerson.emailinst.strip()
        city = ePerson.ciudad if ePerson.ciudad else "Guayaquil"
        if not self.username == self.user.username:
            isUpdate = True
            self.username = self.user.username
        if not self.first_name == first_name:
            isUpdate = True
            self.first_name = first_name
        if not self.last_name == last_name:
            isUpdate = True
            self.last_name = last_name
        if not self.email == email:
            isUpdate = True
            self.email = email
        if not self.city == city:
            isUpdate = True
            self.city = city
        return isUpdate

    def set_password(self, pwd):
        self.password = md5(pwd.encode("utf-8")).hexdigest()

    def check_password(self, pwd):
        return self.password == md5(pwd.encode("utf-8")).hexdigest()

    def save(self, *args, **kwargs):
        super(UserAuth, self).save(*args, **kwargs)


class EvaVirtual(models.Model):
    class TypesConnections(models.TextChoices):
        NINGUNA = 'ninguna', "NINGUNA"
        EVA_1 = 'moodle_eva_1', "EVA 1"
        EVA_2 = 'moodle_eva_2', "EVA 2"
        EVA_3 = 'moodle_eva_3', "EVA 3"

    type_connection = models.CharField(choices=TypesConnections.choices, max_length=50, default=TypesConnections.NINGUNA, verbose_name=u'Tipo de conexión')
    name = models.CharField(default='', max_length=150, verbose_name=u'Nombre', unique=True)
    name_key = models.CharField(default='', max_length=50, verbose_name=u'Nombre Corto', unique=True)
    url = models.CharField(blank=True, null=True, max_length=500, verbose_name=u'URL')
    prefix_db = models.CharField(blank=True, null=True, max_length=50, verbose_name=u'Prefijo de BD')
    token = models.CharField(blank=True, null=True, max_length=500, verbose_name=u'Token')
    role_teacher = models.IntegerField(blank=True, null=True, verbose_name=u'Rol de Profesor')
    role_student = models.IntegerField(blank=True, null=True, verbose_name=u'Rol de Estudiante')
    category_id = models.IntegerField(blank=True, null=True, verbose_name=u'ID Categoria')
    is_active = models.BooleanField(default=True, verbose_name=u'¿Está activo?')

    def __str__(self):
        name = self.name_key if self.name_key else self.name
        if self.url:
            name = "%s (%s)" % (name, self.url)
        return u'%s' % name.strip()

    class Meta:
        verbose_name = u"EVA Virtual"
        verbose_name_plural = u"EVAs virtuales"
        ordering = ['name']
        # unique_together = ('',)

    def has_web_service_data(self):
        return False if not self.url or not self.prefix_db or not self.token or not self.role_student or not self.role_teacher or not self.category_id else True

    def save(self, *args, **kwargs):
        self.name = self.name.strip()
        self.name_key = self.name_key.strip()
        super(EvaVirtual, self).save(*args, **kwargs)

templates/pro_clases/adddeberesbs.html
{% extends "formbs.html" %}
{% block heading %}
    <script>
        $("#id_nombre,#id_archivo,#id_materia,#id_leccionesgrupo").addClass("validate[required]");
        $(function() {
            $("#id_fechaentrega").datepicker({format:"dd-mm-yyyy"});
        });
    </script>
{% endblock %}
{% block titulo %}Adicionar Deber{% endblock %}
{% block formaction %}/pro_clases{% endblock %}
{% block formtagextra %}enctype="multipart/form-data"{% endblock %}
{% block formextra %}
    <input type='hidden' name='action' value='adddeberes'/>
    <input type='hidden' name='materia' value='{{ materia.id }}'/>
    <input type="hidden" name='lecciongrupo' value='{{ lecciongrupo.id }}'/>
{% endblock %}
{% block formback %}/pro_clases?action=view&id={{ lecciongrupo.id }}{% endblock %}
{% block buttonname %}Guardar Deber{% endblock %}

templates/pro_clases/adddplanclase.html
{% extends "formbs.html" %}
{% block heading %}
    <script>
        $("#id_nombre,#id_archivo,#id_materia,#id_leccionesgrupo").addClass("validate[required]");
        $(function() {
            $("#id_fechaentrega").datepicker({format:"dd-mm-yyyy"});
        });
    </script>
{% endblock %}
{% block titulo %}Adicionar Plan de Clase{% endblock %}
{% block formaction %}/pro_clases{% endblock %}
{% block formtagextra %}enctype="multipart/form-data"{% endblock %}
{% block formextra %}
    <input type='hidden' name='action' value='addplanclase'/>
    <input type='hidden' name='materia' value='{{ materia.id }}'/>
    <input type="hidden" name='lecciongrupo' value='{{ lecciongrupo.id }}'/>
{% endblock %}
{% block formback %}/pro_clases?action=view&id={{ lecciongrupo.id }}{% endblock %}
{% block buttonname %}Guardar Plan de Clase{% endblock %}

templates/pro_clases/addmaterial.html
{% extends "formbs.html" %}
{% block heading %}
    <script>
        $("#id_nombre,#id_archivo,#id_materia,#id_leccionesgrupo").addClass("validate[required]");
        $(function() {
        });
    </script>
{% endblock %}
{% block titulo %}Adicionar Material de Apoyo{% endblock %}
{% block formaction %}/pro_clases{% endblock %}
{% block formtagextra %}enctype="multipart/form-data"{% endblock %}
{% block formextra %}
    <input type='hidden' name='action' value='addmaterial'/>
    <input type='hidden' name='materia' value='{{ materia.id }}'/>
    <input type="hidden" name='lecciongrupo' value='{{ lecciongrupo.id }}'/>
{% endblock %}
{% block formback %}/pro_clases?action=view&id={{ lecciongrupo.id }}{% endblock %}
{% block buttonname %}Guardar Material de Apoyo{% endblock %}

templates/pro_clases/clasesbs.html
{% extends "basebs.html" %}
{% block heading %}
    <script type="text/javascript">
        $(function() {
            var valida=0

            function showLocation(pos) {
{#                          valida = 1;#}
            }

            function errorHandler(err) {
              if(err.code == 1) {
                   valida = 1;
{#                    alert("Error: Acceso Denegado encienda el gps!");#}
              }else if( err.code == 2) {
{#                            alert("Error: la posición no está disponible!");#}
              }
            }
            getLocation();
            function getLocation(){

               if(navigator.geolocation){
                  // timeout at 60000 milliseconds (60 seconds)
                  var options = {timeout:60000};
                  navigator.geolocation.getCurrentPosition(showLocation,
                                                           errorHandler,
                                                           options);
               }else{
                  alert("Lo sentimos, navegador no soporta geolocalización!");
               }
            }
            actualizaMaterias = function(id) {
                location.href = "/pro_clases?filter="+id;
            };

            $("#materiassel").change(function() {
                var id = $(this).val();
                actualizaMaterias(id);
            });


            $(".valida").click(function() {
{#                alert($(this).attr("val"));#}
                var id = $(this).attr("val");
                location.href = "/pro_clases?action=view&id="+id+"&valida="+valida;
            });

            //fix_height();
        });
    </script>
{% endblock %}
{% block canvas %}
    <div class='row-fluid'>
        <div class='span11'>
            <h3>Listado de Lecciones Impartidas o en Curso</h3>
            <h5>-</h5>
        </div>
        <div class='span1'>
            <a href="/" class='btn'><i class="icon-arrow-left"></i> Atras</a>
        </div>
    </div>
    <div class='row-fluid'>
        <div class='span8'>
            <form class="form-inline">
                <select id='materiassel'>
                    <option value=''></option>
                    {% for materia in materias %}
                        <option value='{{ materia.id }}' {% if materia.id == filter.id %}selected="true"{% endif %}>{{ materia.nombre_completo }} {% if materia.nivel.sede %} - {{ materia.nivel.sede }}{% endif %} {% if materia.nivel.carrera %} -  {{ materia.nivel.carrera }}{% endif %} {% if materia.nivel.paralelo %}- {{ materia.nivel.paralelo }}{% endif %} {% if not materia.nivel.carrera %} ({{ materia.nivel.coordinacion.nombre }}){% endif %}</option>
                    {% endfor %}
                </select>
            </form>
        </div>
        <div class='span4'>

            {% if filter %}
                <a href="/pro_clases" id='allresults' class='btn btn-info'><i class="icon-search icon-white"></i> Todos</a>
            {% endif %}
        </div>
    </div>
    <div class='row-fluid'>
        <div class='span12'>
        <table class='table table-bordered table-striped' cellpadding="0" cellspacing="0">
            <thead>
            <tr>
                <th>Clase</th>
                <th>Grupos</th>
                <th>Fecha</th>
                <th>Hora Entrada</th>
                <th>Hora Salida</th>
                <th>Asistencia</th>
                <th>Abierta</th>
            </tr>
            </thead>
            <tbody>
            {% for lecciongrupo in leccionesgrupo %}
                <tr>
                    <td>
                        <a href='#' class='valida' val='{{ lecciongrupo.id }}'>
                            <span class='smaller'><b>{{ lecciongrupo.materia.nombre_completo }}</b><br/>
                                <span class='smaller2'>{{ lecciongrupo.turno }}<br/>
                                Aula: {{ lecciongrupo.aula }}<br/>
                                </span>
                            </span>
                        </a>
                    </td>
                    <td>
                        {{ lecciongrupo.materia.nivel.periodo.periodo_repr }}<br>
                        {% for leccion in lecciongrupo.lecciones.all %}
                            - {{ leccion.clase.materia.nivel }}<br/>
                        {% endfor %}

                    </td>
                    <td>{{ lecciongrupo.fecha|date:"d-m-Y" }}</td>
                    <td>{{ lecciongrupo.horaentrada }}</td>
                    <td>
                        {% if not lecciongrupo.abierta %}
                            {{ lecciongrupo.horasalida }}
                        {% endif %}
                    </td>
                    <td>
                        {{ lecciongrupo.asistencia_real }}/{{ lecciongrupo.asistencia_plan }} ({{ lecciongrupo.porciento_asistencia }}%)
                    </td>
                    <td align='center'>
                        {% if lecciongrupo.abierta %}
                            <img src='/static/images/16/true.png' alt='Si' border='0'/>
                        {% else %}
                            <img src='/static/images/16/false.png' alt='No' border='0'/>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            {% if not leccionesgrupo %}
                <tr>
                    <td colspan="7">
                        NO TIENE CLASES EN EL PERIODO
                    </td>
                </tr>
            {% endif %}
            </tbody>
        </table>
        </div>
    </div>
    <div class='row-fluid'>
        <div class="span12">
            <div class='pagination'>
                 <ul>
                    {% for pagenumber in paging.page_range %}
                        <li {% if pagenumber == page.number %}class='active'{% endif %}><a href="/pro_clases?page={{ pagenumber }}{% if filter %}&filter={{ filter.id }}{% endif %}">{{ pagenumber }}</a></li>
                    {% endfor %}
                 </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/pro_clases/motivo_apertura.html
{% extends "formbs.html" %}
{% block extraheading %}
    <style>
        #formulary table td input#id_email { text-transform: none; }
    </style>
{% endblock %}
{% block javascript %}
    $("#id_fecha").datepicker({format:"dd-mm-yyyy"});
    $("#id_motivo, #id_fecha, #id_especie").addClass("validate[required]");
    $("#id_especie").addClass("input-medium");
    $("#id_motivo").focus();

    var caracteres="º\·!|#($~%&¬/<)='?¿¡`]^[+*´¨ç}>;{,:@1234567890";

        function tiene_caracteres(texto){
           var num = 0;
           for(i=0; i<texto.length; i++){
              if (caracteres.indexOf(texto.charAt(i),0)!=-1){
                  num = num + 1;
              }
           }
           return num;
        }

    $('#id_motivo').change(function(){
        var v = $("#id_motivo").val();
        var c = tiene_caracteres(v);

        if($("#id_motivo").val() != ""){
           if(c == 0 ){
                if(v.split('').length > 5){
                  $("#id_motivo").focus();
                  $($("#id_motivo").get(0).parentNode).find(".help-text").html("");
                  $("#formbutton").attr("disabled",false)
                }
                else{
                    $($("#id_motivo").get(0).parentNode).find(".help-text").html("<span style='color: darkred'><i>Ingrese motivo v&aacute;lido. </i></span>");
                    $("#formbutton").attr("disabled",true)
                    }
           }
           else{
                $($("#id_motivo").get(0).parentNode).find(".help-text").html("<span style='color: darkred'><i>El motivo no debe contener caracteres especiales, ingresar correctamente. </i></span>");
                $("#formbutton").attr("disabled",true)
           }
        }
        else{
                $("#id_motivo").focus();
                $($("#id_motivo").get(0).parentNode).find(".help-text").html("<span style='color: darkred'><i>El motivo debe ser ingresado. </i></span>");
                $("#formbutton").attr("disabled",true)
            }
    });

{% endblock %}
{% block titulo %}
    <p style="color: red">Estimado Docente: Ha excedido el tiempo limite de apertura de clase <br>
    Por Favor Ingrese el Motivo del Inconveniente.</p>
{% endblock %}
{% block formaction %}/pro_clases{% endblock %}
{% block formextra %}
    <input type='hidden' name='action' value='nuevaleccion'/>
    <input type='hidden' name='turno' value="{{ turno.id }}"/>
    <input type='hidden' name='profesor' value="{{ profesor.id }}"/>
    <input type='hidden' name='aula' value="{{ aula.id }}"/>
    <input type='hidden' name='dia' value="{{ dia }}"/>
    <input type='hidden' name='valida' value="{{ valida }}"/>
    <input type='hidden' name='claseid' value="{{ claseid }}"/>
{% endblock %}
{#{% block formback %}/matriculas?action=matricula&id={{ matricula.nivel.id }}{% endblock %}#}
{% block formback %}/pro_clases{% endblock %}
{% block buttonname %}Abrir Clase{% endblock %}